
var Wa;Wa||(Wa=typeof Module !== 'undefined' ? Module : {});
module.exports=function(M){function Xa(a,b,c,e){a||(a=this);this.parent=a;this.i=a.i;this.la=null;this.id=d.Zb++;this.name=b;this.mode=c;this.f={};this.g={};this.rdev=e}function fa(a,b){throw b;}function Ya(a){Array.isArray(a)||a instanceof ArrayBuffer?a=new Uint8Array(a):a?a instanceof Uint8Array||(a=new Uint8Array(a.buffer)):a=new Uint8Array(0);return a}function Za(a){var b=[];return function(c,e){if(e&&b.length)return a(R(b,0));10===c||13===c?(S&&b.push(c),a(R(b,0)),b=[]):0!==c&&b.push(c)}}function xb(a){return f.locateFile?
f.locateFile(a,N):N+a}function ha(a,b){a||B("Assertion failed: "+b)}function R(a,b,c){var e=b+c;for(c=b;a[c]&&!(c>=e);)++c;if(16<c-b&&a.subarray&&$a)return $a.decode(a.subarray(b,c));for(e="";b<c;){var g=a[b++];if(g&128){var h=a[b++]&63;if(192==(g&224))e+=String.fromCharCode((g&31)<<6|h);else{var l=a[b++]&63;g=224==(g&240)?(g&15)<<12|h<<6|l:(g&7)<<18|h<<12|l<<6|a[b++]&63;65536>g?e+=String.fromCharCode(g):(g-=65536,e+=String.fromCharCode(55296|g>>10,56320|g&1023))}}else e+=String.fromCharCode(g)}return e}
function ba(a,b){return a?R(V,a,b):""}function W(a,b,c,e){if(!(0<e))return 0;var g=c;e=c+e-1;for(var h=0;h<a.length;++h){var l=a.charCodeAt(h);if(55296<=l&&57343>=l){var n=a.charCodeAt(++h);l=65536+((l&1023)<<10)|n&1023}if(127>=l){if(c>=e)break;b[c++]=l}else{if(2047>=l){if(c+1>=e)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=e)break;b[c++]=224|l>>12}else{if(c+3>=e)break;b[c++]=240|l>>18;b[c++]=128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-g}function ia(a){for(var b=0,c=0;c<a.length;++c){var e=
a.charCodeAt(c);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++c)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:b+4}return b}function ab(a){var b=ia(a)+1,c=ta(b);c&&W(a,I,c,b);return c}function bb(a){var b=ia(a)+1,c=Ja(b);W(a,I,c,b);return c}function ja(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(f);else{var c=b.Sb;"number"===typeof c?void 0===b.Ba?f.dynCall_v(c):f.dynCall_vi(c,b.Ba):c(void 0===b.Ba?null:b.Ba)}}}function cb(){X++;f.monitorRunDependencies&&f.monitorRunDependencies(X)}
function Ka(){X--;f.monitorRunDependencies&&f.monitorRunDependencies(X);if(0==X&&(null!==La&&(clearInterval(La),La=null),ka)){var a=ka;ka=null;a()}}function B(a){if(f.onAbort)f.onAbort(a);ca(a);F(a);Ma=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Na(a,b){return String.prototype.startsWith?a.startsWith(b):0===a.indexOf(b)}function db(a){return Na(a,"data:application/octet-stream;base64,")}function eb(){try{if(la)return new Uint8Array(la);
if(ua)return ua(O);throw"both async and sync fetching of the wasm failed";}catch(a){B(a)}}function yb(){return la||!va&&!Q||"function"!==typeof fetch||Na(O,"file://")?new Promise(function(a){a(eb())}):fetch(O,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+O+"'";return a.arrayBuffer()}).catch(function(){return eb()})}function zb(a){return a.replace(/\b_Z[\w\d_]+/g,function(b){return b===b?b:b+" ["+b+"]"})}function Y(a){return m[fb()>>2]=a}function wa(){void 0===
wa.start&&(wa.start=Date.now());return 1E3*(Date.now()-wa.start)|0}function ma(){if(!ma.B){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:xa||"./this.program"},b;for(b in gb)a[b]=gb[b];var c=[];for(b in a)c.push(b+"="+a[b]);ma.B=c}return ma.B}function hb(a,b){a=new Date(1E3*m[a>>2]);m[b>>2]=a.getUTCSeconds();m[b+4>>2]=a.getUTCMinutes();m[b+8>>2]=a.getUTCHours();
m[b+12>>2]=a.getUTCDate();m[b+16>>2]=a.getUTCMonth();m[b+20>>2]=a.getUTCFullYear()-1900;m[b+24>>2]=a.getUTCDay();m[b+36>>2]=0;m[b+32>>2]=0;m[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;m[b+40>>2]=Ab;return b}function ya(){function a(h){return(h=h.toTimeString().match(/\(([A-Za-z ]+)\)$/))?h[1]:"GMT"}if(!ya.B){ya.B=!0;m[ib()>>2]=60*(new Date).getTimezoneOffset();var b=(new Date).getFullYear(),c=new Date(b,0,1);b=new Date(b,6,1);m[jb()>>2]=Number(c.getTimezoneOffset()!=b.getTimezoneOffset());
var e=a(c),g=a(b);e=ab(e);g=ab(g);b.getTimezoneOffset()<c.getTimezoneOffset()?(m[da()>>2]=e,m[da()+4>>2]=g):(m[da()>>2]=g,m[da()+4>>2]=e)}}function kb(a,b){ya();a=new Date(1E3*m[a>>2]);m[b>>2]=a.getSeconds();m[b+4>>2]=a.getMinutes();m[b+8>>2]=a.getHours();m[b+12>>2]=a.getDate();m[b+16>>2]=a.getMonth();m[b+20>>2]=a.getFullYear()-1900;m[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1);m[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;m[b+36>>2]=-(60*a.getTimezoneOffset());var e=(new Date(a.getFullYear(),
6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(e!=c&&a.getTimezoneOffset()==Math.min(c,e))|0;m[b+32>>2]=a;a=m[da()+(a?4:0)>>2];m[b+40>>2]=a;return b}function za(a){return 0===a%4&&(0!==a%100||0===a%400)}function Oa(a,b){for(var c=0,e=0;e<=b;c+=a[e++]);return c}function Aa(a,b){for(a=new Date(a.getTime());0<b;){var c=za(a.getFullYear()),e=a.getMonth();c=(c?Ba:Ca)[e];if(b>c-a.getDate())b-=c-a.getDate()+1,a.setDate(1),11>e?a.setMonth(e+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+
b);break}}return a}function Da(a,b,c){c=0<c?c:ia(a)+1;c=Array(c);a=W(a,c,0,c.length);b&&(c.length=a);return c}function Pa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}function Qa(a){function b(){if(!Ea&&(Ea=!0,f.calledRun=!0,!Ma)){f.noFSInit||d.W.Ha||d.W();T.W();ja(lb);d.nb=!1;ja(Bb);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(mb){var c=a,e=f._main;c=c||[];var g=c.length+1,h=Ja(4*(g+1));m[h>>2]=bb(xa);for(var l=1;l<g;l++)m[(h>>2)+l]=bb(c[l-1]);
m[(h>>2)+g]=0;try{var n=e(g,h);nb(n,!0)}catch(t){t instanceof Pa||("unwind"==t?Fa=!0:((c=t)&&"object"===typeof t&&t.stack&&(c=[t,t.stack]),F("exception thrown: "+c),fa(1,t)))}finally{}}if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)ob.unshift(f.postRun.shift());ja(ob)}}a=a||na;if(!(0<X)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)pb.unshift(f.preRun.shift());ja(pb);0<X||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},
1);b()},1)):b())}}function nb(a,b){if(!b||!Fa||0!==a){if(!Fa&&(Ma=!0,ja(Cb),d.quit(),f.onExit))f.onExit(a);fa(a,new Pa(a))}}M=M||{};var Db=B,qb,f={};Object.keys(M).forEach(function(a){0>["mounts","MEMFS","onExit","chdir"].indexOf(a)&&(f[a]=M[a])});B=function(a){if(arguments.length)Db(a);else throw new Pa(0);};f.stdin=f.stdin||function(){};f.stdout=f.stdout||Za(function(a){ca(a)});f.stderr=f.stderr||Za(function(a){F(a)});"object"===typeof process&&(f.print=f.print||process.stdout.write.bind(process.stdout),
f.printErr=f.printErr||process.stderr.write.bind(process.stderr));f.quit=function(a){f.stdout(0,!0);f.stderr(0,!0);if(M.onExit)M.onExit(a)};f.preRun=function(){(M.mounts||[]).forEach(function(a){var b=d.eb[a.type];if(!b)throw Error("Bad mount type");var c=a.mountpoint;if(!c.match(/^\/[^\/]+$/)||"/."===c||"/.."===c||"/tmp"===c||"/home"===c||"/dev"===c||"/work"===c)throw Error("Bad mount point");d.mkdir(c);d.i(b,a.opts,c)});d.mkdir("/work");d.chdir(M.chdir||"/work");(M.MEMFS||[]).forEach(function(a){if(a.name.match(/\//))throw Error("Bad file name");
var b=d.open(a.name,"w+");a=Ya(a.data);d.write(b,a,0,a.length);d.close(b)})};f.postRun=function(){var a=Object.create(null);(M.MEMFS||[]).forEach(function(b){a[b.name]=null});qb={MEMFS:function(b){var c=d.h(b).node.c;b=Object.keys(c);c.__proto__&&"__proto__"===c.__proto__.name&&b.push("__proto__");return b.map(function(e){return c[e]})}("/work").filter(function(b){return!(b.name in a)}).map(function(b){var c=Ya(b.c);return{name:b.name,data:c}})}};var oa={},U;for(U in f)f.hasOwnProperty(U)&&(oa[U]=
f[U]);var na=[],xa="./this.program",va=!1,Q=!1,S=!1,rb=!1;va="object"===typeof window;Q="function"===typeof importScripts;S="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;rb=!va&&!S&&!Q;var N="",Ga,Ra;if(S){N=Q?require("path").dirname(N)+"/":__dirname+"/";var pa=function(a,b){Ga||(Ga=require("fs"));Ra||(Ra=require("path"));a=Ra.normalize(a);return Ga.readFileSync(a,b?null:"utf8")};var ua=function(a){a=pa(a,!0);a.buffer||(a=new Uint8Array(a));
ha(a.buffer);return a};1<process.argv.length&&(xa=process.argv[1].replace(/\\/g,"/"));na=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=f);fa=function(a){process.exit(a)};f.inspect=function(){return"[Emscripten Module object]"}}else if(rb)"undefined"!=typeof read&&(pa=function(a){return read(a)}),ua=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");ha("object"===typeof a);return a},"undefined"!=typeof scriptArgs?na=scriptArgs:
"undefined"!=typeof arguments&&(na=arguments),"function"===typeof quit&&(fa=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(va||Q)Q?N=self.location.href:document.currentScript&&(N=document.currentScript.src),N=0!==N.indexOf("blob:")?N.substr(0,N.lastIndexOf("/")+1):"",pa=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},
Q&&(ua=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});var ca=f.print||console.log.bind(console),F=f.printErr||console.warn.bind(console);for(U in oa)oa.hasOwnProperty(U)&&(f[U]=oa[U]);oa=null;f.arguments&&(na=f.arguments);f.thisProgram&&(xa=f.thisProgram);f.quit&&(fa=f.quit);var la;f.wasmBinary&&(la=f.wasmBinary);var Fa;f.noExitRuntime&&(Fa=f.noExitRuntime);"object"!==typeof WebAssembly&&F("no native wasm support detected");
var qa,Eb=new WebAssembly.Table({initial:2920,maximum:2920,element:"anyfunc"}),Ma=!1,$a="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");var I,V,Sa,m,Ta=f.INITIAL_MEMORY||67108864;f.wasmMemory?qa=f.wasmMemory:qa=new WebAssembly.Memory({initial:Ta/65536,maximum:Ta/65536});if(qa)var Ua=qa.buffer;Ta=Ua.byteLength;(function(a){Ua=a;f.HEAP8=I=new Int8Array(a);f.HEAP16=Sa=new Int16Array(a);f.HEAP32=m=new Int32Array(a);f.HEAPU8=
V=new Uint8Array(a);f.HEAPU16=new Uint16Array(a);f.HEAPU32=new Uint32Array(a);f.HEAPF32=new Float32Array(a);f.HEAPF64=new Float64Array(a)})(Ua);m[583544]=7577216;var pb=[],lb=[],Bb=[],Cb=[],ob=[],ra=Math.abs,Z=Math.ceil,aa=Math.floor,sa=Math.min,X=0,La=null,ka=null;f.preloadedImages={};f.preloadedAudios={};var O="ffmpeg-mp4.wasm";db(O)||(O=xb(O));var z,J;lb.push({Sb:function(){sb()}});var w={qb:function(a){return/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1)},Na:function(a,
b){for(var c=0,e=a.length-1;0<=e;e--){var g=a[e];"."===g?a.splice(e,1):".."===g?(a.splice(e,1),c++):c&&(a.splice(e,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},normalize:function(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=w.Na(a.split("/").filter(function(e){return!!e}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},dirname:function(a){var b=w.qb(a);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b},basename:function(a){if("/"===a)return"/";var b=
a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},extname:function(a){return w.qb(a)[3]},join:function(){var a=Array.prototype.slice.call(arguments,0);return w.normalize(a.join("/"))},v:function(a,b){return w.normalize(a+"/"+b)}},P={resolve:function(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:d.cwd();if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=w.Na(a.split("/").filter(function(e){return!!e}),
!b).join("/");return(b?"/":"")+a||"."},relative:function(a,b){function c(l){for(var n=0;n<l.length&&""===l[n];n++);for(var t=l.length-1;0<=t&&""===l[t];t--);return n>t?[]:l.slice(n,t-n+1)}a=P.resolve(a).substr(1);b=P.resolve(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var e=Math.min(a.length,b.length),g=e,h=0;h<e;h++)if(a[h]!==b[h]){g=h;break}e=[];for(h=g;h<a.length;h++)e.push("..");e=e.concat(b.slice(g));return e.join("/")}},T={tb:[],W:function(){},ef:function(){},register:function(a,b){T.tb[a]=
{input:[],output:[],ba:b};d.Sa(a,T.g)},g:{open:function(a){var b=T.tb[a.node.rdev];if(!b)throw new d.b(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.ba.flush(a.tty)},flush:function(a){a.tty.ba.flush(a.tty)},read:function(a,b,c,e){if(!a.tty||!a.tty.ba.jb)throw new d.b(60);for(var g=0,h=0;h<e;h++){try{var l=a.tty.ba.jb(a.tty)}catch(n){throw new d.b(29);}if(void 0===l&&0===g)throw new d.b(6);if(null===l||void 0===l)break;g++;b[c+h]=l}g&&(a.node.timestamp=Date.now());return g},write:function(a,b,
c,e){if(!a.tty||!a.tty.ba.Oa)throw new d.b(60);try{for(var g=0;g<e;g++)a.tty.ba.Oa(a.tty,b[c+g])}catch(h){throw new d.b(29);}e&&(a.node.timestamp=Date.now());return g}},Nb:{jb:function(a){if(!a.input.length){var b=null;if(S){var c=Buffer.B?Buffer.B(256):new Buffer(256),e=0;try{e=Ga.readSync(process.stdin.fd,c,0,256,null)}catch(g){if(-1!=g.toString().indexOf("EOF"))e=0;else throw g;}0<e?b=c.slice(0,e).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),
null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Da(b,!0)}return a.input.shift()},Oa:function(a,b){null===b||10===b?(ca(R(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ca(R(a.output,0)),a.output=[])}},Mb:{Oa:function(a,b){null===b||10===b?(F(R(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(F(R(a.output,0)),a.output=[])}}},v={M:null,i:function(){return v.createNode(null,
"/",16895,0)},createNode:function(a,b,c,e){if(d.Ub(c)||d.isFIFO(c))throw new d.b(63);v.M||(v.M={dir:{node:{D:v.f.D,o:v.f.o,lookup:v.f.lookup,F:v.f.F,rename:v.f.rename,unlink:v.f.unlink,rmdir:v.f.rmdir,readdir:v.f.readdir,symlink:v.f.symlink},stream:{A:v.g.A}},file:{node:{D:v.f.D,o:v.f.o},stream:{A:v.g.A,read:v.g.read,write:v.g.write,ia:v.g.ia,aa:v.g.aa,Z:v.g.Z}},link:{node:{D:v.f.D,o:v.f.o,readlink:v.f.readlink},stream:{}},Ya:{node:{D:v.f.D,o:v.f.o},stream:d.Eb}});c=d.createNode(a,b,c,e);d.m(c.mode)?
(c.f=v.M.dir.node,c.g=v.M.dir.stream,c.c={}):d.isFile(c.mode)?(c.f=v.M.file.node,c.g=v.M.file.stream,c.j=0,c.c=null):d.R(c.mode)?(c.f=v.M.link.node,c.g=v.M.link.stream):d.ja(c.mode)&&(c.f=v.M.Ya.node,c.g=v.M.Ya.stream);c.timestamp=Date.now();a&&(a.c[b]=c);return c},Ve:function(a){if(a.c&&a.c.subarray){for(var b=[],c=0;c<a.j;++c)b.push(a.c[c]);return b}return a.c},We:function(a){return a.c?a.c.subarray?a.c.subarray(0,a.j):new Uint8Array(a.c):new Uint8Array(0)},cb:function(a,b){var c=a.c?a.c.length:
0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.c,a.c=new Uint8Array(b),0<a.j&&a.c.set(c.subarray(0,a.j),0))},fc:function(a,b){if(a.j!=b)if(0==b)a.c=null,a.j=0;else{if(!a.c||a.c.subarray){var c=a.c;a.c=new Uint8Array(b);c&&a.c.set(c.subarray(0,Math.min(b,a.j)))}else if(a.c||(a.c=[]),a.c.length>b)a.c.length=b;else for(;a.c.length<b;)a.c.push(0);a.j=b}},f:{D:function(a){var b={};b.dev=d.ja(a.mode)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;
d.m(a.mode)?b.size=4096:d.isFile(a.mode)?b.size=a.j:d.R(a.mode)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.N=4096;b.blocks=Math.ceil(b.size/b.N);return b},o:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&v.fc(a,b.size)},lookup:function(){throw d.Fa[44];},F:function(a,b,c,e){return v.createNode(a,b,c,e)},rename:function(a,b,c){if(d.m(a.mode)){try{var e=d.K(b,
c)}catch(h){}if(e)for(var g in e.c)throw new d.b(55);}delete a.parent.c[a.name];a.name=c;b.c[c]=a;a.parent=b},unlink:function(a,b){delete a.c[b]},rmdir:function(a,b){var c=d.K(a,b),e;for(e in c.c)throw new d.b(55);delete a.c[b]},readdir:function(a){var b=[".",".."],c;for(c in a.c)a.c.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=v.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(!d.R(a.mode))throw new d.b(28);return a.link}},g:{read:function(a,b,c,e,g){var h=a.node.c;
if(g>=a.node.j)return 0;a=Math.min(a.node.j-g,e);if(8<a&&h.subarray)b.set(h.subarray(g,g+a),c);else for(e=0;e<a;e++)b[c+e]=h[g+e];return a},write:function(a,b,c,e,g,h){if(!e)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.c||a.c.subarray)){if(h)return a.c=b.subarray(c,c+e),a.j=e;if(0===a.j&&0===g)return a.c=b.slice(c,c+e),a.j=e;if(g+e<=a.j)return a.c.set(b.subarray(c,c+e),g),e}v.cb(a,g+e);if(a.c.subarray&&b.subarray)a.c.set(b.subarray(c,c+e),g);else for(h=0;h<e;h++)a.c[g+h]=b[c+h];a.j=
Math.max(a.j,g+e);return e},A:function(a,b,c){1===c?b+=a.position:2===c&&d.isFile(a.node.mode)&&(b+=a.node.j);if(0>b)throw new d.b(28);return b},ia:function(a,b,c){v.cb(a.node,b+c);a.node.j=Math.max(a.node.j,b+c)},aa:function(a,b,c,e,g,h,l){if(!d.isFile(a.node.mode))throw new d.b(43);a=a.node.c;if(l&2||a.buffer!==b.buffer){if(0<g||g+e<a.length)a.subarray?a=a.subarray(g,g+e):a=Array.prototype.slice.call(a,g,g+e);g=!0;l=b.buffer==I.buffer;e=ta(e);if(!e)throw new d.b(48);(l?I:b).set(a,e)}else g=!1,e=
a.byteOffset;return{ec:e,Bb:g}},Z:function(a,b,c,e,g){if(!d.isFile(a.node.mode))throw new d.b(43);if(g&2)return 0;v.g.write(a,b,0,e,c,!1);return 0}}},Fb={ee:63,Ed:44,re:71,Zc:27,ad:29,ae:60,nc:1,Fd:45,wc:8,Fc:12,tc:6,Be:6,Jd:48,oc:2,Sc:21,Sd:105,Dc:10,Rc:20,Ce:75,Dd:43,Ud:54,cd:31,$c:28,yd:41,qd:33,Zd:59,ye:74,Tc:22,Od:51,qe:70,ne:69,rd:34,ge:64,Oc:18,ke:68,Kd:49,Wc:24,Gc:106,ed:156,gd:107,hd:108,od:109,ze:110,Bd:111,dd:112,Lc:16,Gd:46,vc:113,zc:114,De:115,zd:104,Ac:103,Bc:102,Mc:16,Cc:101,Qd:100,
Cd:116,ve:117,Pd:118,Ld:119,Md:120,me:121,Hd:47,rc:122,se:123,Hc:124,he:65,td:36,Pc:125,yc:9,$d:126,xc:127,le:128,jd:129,kd:130,nd:131,md:132,ld:133,Rd:52,Vd:55,ud:37,pd:32,be:138,fe:139,Kc:15,Ad:42,sc:5,je:67,Xd:57,Nd:50,oe:140,Jc:14,pc:3,Ic:13,xd:40,vd:38,we:73,Uc:142,Vc:23,Yc:26,uc:7,Nc:17,sd:35,ie:66,pe:137,qc:4,wd:39,bd:30,Td:53,xe:141,Ae:136,Qc:19,te:72,Yd:138,Id:148,Xc:25,ce:61,Ec:11,Wd:56,de:62,ue:135},u={qa:!1,Ta:function(){u.qa=!!process.platform.match(/^win/);var a=process.binding("constants");
a.fs&&(a=a.fs);u.fb={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY}},Wa:function(a){return Buffer.alloc?Buffer.from(a):new Buffer(a)},u:function(a){return Fb[a.code]},i:function(a){return u.createNode(null,"/",u.T(a.da.root),0)},createNode:function(a,b,c){if(!d.m(c)&&!d.isFile(c)&&!d.R(c))throw new d.b(28);a=d.createNode(a,b,c);a.f=u.f;a.g=u.g;return a},T:function(a){try{var b=H.lstatSync(a);u.qa&&(b.mode=b.mode|(b.mode&292)>>2)}catch(c){if(!c.code)throw c;
throw new d.b(u.u(c));}return b.mode},G:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.i.da.root);b.reverse();return w.join.apply(null,b)},Rb:function(a){a&=-2656257;var b=0,c;for(c in u.fb)a&c&&(b|=u.fb[c],a^=c);if(a)throw new d.b(28);return b},f:{D:function(a){a=u.G(a);try{var b=H.lstatSync(a)}catch(c){if(!c.code)throw c;throw new d.b(u.u(c));}u.qa&&!b.N&&(b.N=4096);u.qa&&!b.blocks&&(b.blocks=(b.size+b.N-1)/b.N|0);return{dev:b.dev,ino:b.ino,mode:b.mode,nlink:b.nlink,uid:b.uid,
gid:b.gid,rdev:b.rdev,size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,N:b.N,blocks:b.blocks}},o:function(a,b){var c=u.G(a);try{void 0!==b.mode&&(H.chmodSync(c,b.mode),a.mode=b.mode),void 0!==b.size&&H.truncateSync(c,b.size)}catch(e){if(!e.code)throw e;throw new d.b(u.u(e));}},lookup:function(a,b){var c=w.v(u.G(a),b);c=u.T(c);return u.createNode(a,b,c)},F:function(a,b,c,e){a=u.createNode(a,b,c,e);b=u.G(a);try{d.m(a.mode)?H.mkdirSync(b,a.mode):H.writeFileSync(b,"",{mode:a.mode})}catch(g){if(!g.code)throw g;
throw new d.b(u.u(g));}return a},rename:function(a,b,c){var e=u.G(a);b=w.v(u.G(b),c);try{H.renameSync(e,b)}catch(g){if(!g.code)throw g;throw new d.b(u.u(g));}a.name=c},unlink:function(a,b){a=w.v(u.G(a),b);try{H.unlinkSync(a)}catch(c){if(!c.code)throw c;throw new d.b(u.u(c));}},rmdir:function(a,b){a=w.v(u.G(a),b);try{H.rmdirSync(a)}catch(c){if(!c.code)throw c;throw new d.b(u.u(c));}},readdir:function(a){a=u.G(a);try{return H.readdirSync(a)}catch(b){if(!b.code)throw b;throw new d.b(u.u(b));}},symlink:function(a,
b,c){a=w.v(u.G(a),b);try{H.symlinkSync(c,a)}catch(e){if(!e.code)throw e;throw new d.b(u.u(e));}},readlink:function(a){var b=u.G(a);try{return b=H.readlinkSync(b),b=tb.relative(tb.resolve(a.i.da.root),b)}catch(c){if(!c.code)throw c;throw new d.b(u.u(c));}}},g:{open:function(a){var b=u.G(a.node);try{d.isFile(a.node.mode)&&(a.na=H.openSync(b,u.Rb(a.flags)))}catch(c){if(!c.code)throw c;throw new d.b(u.u(c));}},close:function(a){try{d.isFile(a.node.mode)&&a.na&&H.closeSync(a.na)}catch(b){if(!b.code)throw b;
throw new d.b(u.u(b));}},read:function(a,b,c,e,g){if(0===e)return 0;try{return H.readSync(a.na,u.Wa(b.buffer),c,e,g)}catch(h){throw new d.b(u.u(h));}},write:function(a,b,c,e,g){try{return H.writeSync(a.na,u.Wa(b.buffer),c,e,g)}catch(h){throw new d.b(u.u(h));}},A:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&d.isFile(a.node.mode))try{b+=H.fstatSync(a.na).size}catch(e){throw new d.b(u.u(e));}if(0>b)throw new d.b(28);return b},aa:function(a,b,c,e,g){if(!d.isFile(a.node.mode))throw new d.b(43);
var h=ta(e);ha(0===c);u.g.read(a,b,h+c,e,g);return{ec:h,Bb:!0}},Z:function(a,b,c,e,g){if(!d.isFile(a.node.mode))throw new d.b(43);if(g&2)return 0;u.g.write(a,b,0,e,c,!1);return 0}}},G={ya:16895,ha:33279,Qa:null,i:function(a){function b(h){h=h.split("/");for(var l=e,n=0;n<h.length-1;n++){var t=h.slice(0,n+1).join("/");g[t]||(g[t]=G.createNode(l,h[n],G.ya,0));l=g[t]}return l}function c(h){h=h.split("/");return h[h.length-1]}ha(Q);G.Qa||(G.Qa=new FileReaderSync);var e=G.createNode(null,"/",G.ya,0),g=
{};Array.prototype.forEach.call(a.da.files||[],function(h){G.createNode(b(h.name),c(h.name),G.ha,0,h,h.lastModifiedDate)});(a.da.blobs||[]).forEach(function(h){G.createNode(b(h.name),c(h.name),G.ha,0,h.data)});(a.da.packages||[]).forEach(function(h){h.metadata.files.forEach(function(l){var n=l.filename.substr(1);G.createNode(b(n),c(n),G.ha,0,h.blob.slice(l.start,l.end))})});return e},createNode:function(a,b,c,e,g,h){e=d.createNode(a,b,c);e.mode=c;e.f=G.f;e.g=G.g;e.timestamp=(h||new Date).getTime();
ha(G.ha!==G.ya);c===G.ha?(e.size=g.size,e.c=g):(e.size=4096,e.c={});a&&(a.c[b]=e);return e},f:{D:function(a){return{dev:1,ino:a.id,mode:a.mode,nlink:1,uid:0,gid:0,rdev:void 0,size:a.size,atime:new Date(a.timestamp),mtime:new Date(a.timestamp),ctime:new Date(a.timestamp),N:4096,blocks:Math.ceil(a.size/4096)}},o:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp)},lookup:function(){throw new d.b(44);},F:function(){throw new d.b(63);},rename:function(){throw new d.b(63);
},unlink:function(){throw new d.b(63);},rmdir:function(){throw new d.b(63);},readdir:function(a){var b=[".",".."],c;for(c in a.c)a.c.hasOwnProperty(c)&&b.push(c);return b},symlink:function(){throw new d.b(63);},readlink:function(){throw new d.b(63);}},g:{read:function(a,b,c,e,g){if(g>=a.node.size)return 0;a=a.node.c.slice(g,g+e);e=G.Qa.readAsArrayBuffer(a);b.set(new Uint8Array(e),c);return a.size},write:function(){throw new d.b(29);},A:function(a,b,c){1===c?b+=a.position:2===c&&d.isFile(a.node.mode)&&
(b+=a.node.size);if(0>b)throw new d.b(28);return b}}},d={root:null,ma:[],ab:{},streams:[],Zb:1,L:null,$a:"/",Ha:!1,nb:!0,s:{},sb:{pb:{xb:1,yb:2}},b:null,Fa:{},eb:null,ta:0,Xe:function(a){if(!(a instanceof d.b)){a:{var b=Error();if(!b.stack){try{throw Error();}catch(c){b=c}if(!b.stack){b="(no stack trace available)";break a}}b=b.stack.toString()}f.extraStackTrace&&(b+="\n"+f.extraStackTrace());b=zb(b);throw a+" : "+b;}return Y(a.l)},h:function(a,b){a=P.resolve(d.cwd(),a);b=b||{};if(!a)return{path:"",
node:null};var c={Ea:!0,Ra:0},e;for(e in c)void 0===b[e]&&(b[e]=c[e]);if(8<b.Ra)throw new d.b(32);a=w.Na(a.split("/").filter(function(l){return!!l}),!1);var g=d.root;c="/";for(e=0;e<a.length;e++){var h=e===a.length-1;if(h&&b.parent)break;g=d.K(g,a[e]);c=w.v(c,a[e]);d.X(g)&&(!h||h&&b.Ea)&&(g=g.la.root);if(!h||b.H)for(h=0;d.R(g.mode);)if(g=d.readlink(c),c=P.resolve(w.dirname(c),g),g=d.h(c,{Ra:b.Ra}).node,40<h++)throw new d.b(32);}return{path:c,node:g}},I:function(a){for(var b;;){if(d.pa(a))return a=
a.i.ob,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},Ga:function(a,b){for(var c=0,e=0;e<b.length;e++)c=(c<<5)-c+b.charCodeAt(e)|0;return(a+c>>>0)%d.L.length},lb:function(a){var b=d.Ga(a.parent.id,a.name);a.$=d.L[b];d.L[b]=a},mb:function(a){var b=d.Ga(a.parent.id,a.name);if(d.L[b]===a)d.L[b]=a.$;else for(b=d.L[b];b;){if(b.$===a){b.$=a.$;break}b=b.$}},K:function(a,b){var c=d.Wb(a);if(c)throw new d.b(c,a);for(c=d.L[d.Ga(a.id,b)];c;c=c.$){var e=c.name;if(c.parent.id===a.id&&
e===b)return c}return d.lookup(a,b)},createNode:function(a,b,c,e){a=new d.vb(a,b,c,e);d.lb(a);return a},Ca:function(a){d.mb(a)},pa:function(a){return a===a.parent},X:function(a){return!!a.la},isFile:function(a){return 32768===(a&61440)},m:function(a){return 16384===(a&61440)},R:function(a){return 40960===(a&61440)},ja:function(a){return 8192===(a&61440)},Ub:function(a){return 24576===(a&61440)},isFIFO:function(a){return 4096===(a&61440)},isSocket:function(a){return 49152===(a&49152)},Qb:{r:0,rs:1052672,
"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218},Yb:function(a){var b=d.Qb[a];if("undefined"===typeof b)throw Error("Unknown file open mode: "+a);return b},gb:function(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},S:function(a,b){if(d.nb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0},Wb:function(a){var b=d.S(a,"x");return b?
b:a.f.lookup?0:2},Ma:function(a,b){try{return d.K(a,b),20}catch(c){}return d.S(a,"wx")},ra:function(a,b,c){try{var e=d.K(a,b)}catch(g){return g.l}if(a=d.S(a,"wx"))return a;if(c){if(!d.m(e.mode))return 54;if(d.pa(e)||d.I(e)===d.cwd())return 10}else if(d.m(e.mode))return 31;return 0},Xb:function(a,b){return a?d.R(a.mode)?32:d.m(a.mode)&&("r"!==d.gb(b)||b&512)?31:d.S(a,d.gb(b)):44},wb:4096,$b:function(a,b){b=b||d.wb;for(a=a||0;a<=b;a++)if(!d.streams[a])return a;throw new d.b(33);},P:function(a){return d.streams[a]},
Lb:function(a,b,c){d.za||(d.za=function(){},d.za.prototype={object:{get:function(){return this.node},set:function(h){this.node=h}}});var e=new d.za,g;for(g in a)e[g]=a[g];a=e;b=d.$b(b,c);a.fd=b;return d.streams[b]=a},Fb:function(a){d.streams[a]=null},Eb:{open:function(a){a.g=d.Tb(a.node.rdev).g;a.g.open&&a.g.open(a)},A:function(){throw new d.b(70);}},La:function(a){return a>>8},af:function(a){return a&255},Y:function(a,b){return a<<8|b},Sa:function(a,b){d.ab[a]={g:b}},Tb:function(a){return d.ab[a]},
ib:function(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push.apply(a,c.ma)}return b},rb:function(a,b){function c(l){d.ta--;return b(l)}function e(l){if(l){if(!e.B)return e.B=!0,c(l)}else++h>=g.length&&c(null)}"function"===typeof a&&(b=a,a=!1);d.ta++;1<d.ta&&F("warning: "+d.ta+" FS.syncfs operations in flight at once, probably just doing extra work");var g=d.ib(d.root.i),h=0;g.forEach(function(l){if(!l.type.rb)return e(null);l.type.rb(l,a,e)})},i:function(a,b,c){var e="/"===c,g=!c;if(e&&
d.root)throw new d.b(10);if(!e&&!g){var h=d.h(c,{Ea:!1});c=h.path;h=h.node;if(d.X(h))throw new d.b(10);if(!d.m(h.mode))throw new d.b(54);}b={type:a,da:b,ob:c,ma:[]};a=a.i(b);a.i=b;b.root=a;e?d.root=a:h&&(h.la=b,h.i&&h.i.ma.push(b));return a},hf:function(a){a=d.h(a,{Ea:!1});if(!d.X(a.node))throw new d.b(28);a=a.node;var b=a.la,c=d.ib(b);Object.keys(d.L).forEach(function(e){for(e=d.L[e];e;){var g=e.$;-1!==c.indexOf(e.i)&&d.Ca(e);e=g}});a.la=null;a.i.ma.splice(a.i.ma.indexOf(b),1)},lookup:function(a,
b){return a.f.lookup(a,b)},F:function(a,b,c){var e=d.h(a,{parent:!0}).node;a=w.basename(a);if(!a||"."===a||".."===a)throw new d.b(28);var g=d.Ma(e,a);if(g)throw new d.b(g);if(!e.f.F)throw new d.b(63);return e.f.F(e,a,b,c)},create:function(a,b){return d.F(a,(void 0!==b?b:438)&4095|32768,0)},mkdir:function(a,b){return d.F(a,(void 0!==b?b:511)&1023|16384,0)},bf:function(a,b){a=a.split("/");for(var c="",e=0;e<a.length;++e)if(a[e]){c+="/"+a[e];try{d.mkdir(c,b)}catch(g){if(20!=g.l)throw g;}}},sa:function(a,
b,c){"undefined"===typeof c&&(c=b,b=438);return d.F(a,b|8192,c)},symlink:function(a,b){if(!P.resolve(a))throw new d.b(44);var c=d.h(b,{parent:!0}).node;if(!c)throw new d.b(44);b=w.basename(b);var e=d.Ma(c,b);if(e)throw new d.b(e);if(!c.f.symlink)throw new d.b(63);return c.f.symlink(c,b,a)},rename:function(a,b){var c=w.dirname(a),e=w.dirname(b),g=w.basename(a),h=w.basename(b);try{var l=d.h(a,{parent:!0});var n=l.node;l=d.h(b,{parent:!0});var t=l.node}catch(q){throw new d.b(10);}if(!n||!t)throw new d.b(44);
if(n.i!==t.i)throw new d.b(75);l=d.K(n,g);e=P.relative(a,e);if("."!==e.charAt(0))throw new d.b(28);e=P.relative(b,c);if("."!==e.charAt(0))throw new d.b(55);try{var p=d.K(t,h)}catch(q){}if(l!==p){c=d.m(l.mode);if(g=d.ra(n,g,c))throw new d.b(g);if(g=p?d.ra(t,h,c):d.Ma(t,h))throw new d.b(g);if(!n.f.rename)throw new d.b(63);if(d.X(l)||p&&d.X(p))throw new d.b(10);if(t!==n&&(g=d.S(n,"w")))throw new d.b(g);try{d.s.willMovePath&&d.s.willMovePath(a,b)}catch(q){F("FS.trackingDelegate['willMovePath']('"+a+"', '"+
b+"') threw an exception: "+q.message)}d.mb(l);try{n.f.rename(l,t,h)}catch(q){throw q;}finally{d.lb(l)}try{if(d.s.onMovePath)d.s.onMovePath(a,b)}catch(q){F("FS.trackingDelegate['onMovePath']('"+a+"', '"+b+"') threw an exception: "+q.message)}}},rmdir:function(a){var b=d.h(a,{parent:!0}).node,c=w.basename(a),e=d.K(b,c),g=d.ra(b,c,!0);if(g)throw new d.b(g);if(!b.f.rmdir)throw new d.b(63);if(d.X(e))throw new d.b(10);try{d.s.willDeletePath&&d.s.willDeletePath(a)}catch(h){F("FS.trackingDelegate['willDeletePath']('"+
a+"') threw an exception: "+h.message)}b.f.rmdir(b,c);d.Ca(e);try{if(d.s.onDeletePath)d.s.onDeletePath(a)}catch(h){F("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+h.message)}},readdir:function(a){a=d.h(a,{H:!0}).node;if(!a.f.readdir)throw new d.b(54);return a.f.readdir(a)},unlink:function(a){var b=d.h(a,{parent:!0}).node,c=w.basename(a),e=d.K(b,c),g=d.ra(b,c,!1);if(g)throw new d.b(g);if(!b.f.unlink)throw new d.b(63);if(d.X(e))throw new d.b(10);try{d.s.willDeletePath&&d.s.willDeletePath(a)}catch(h){F("FS.trackingDelegate['willDeletePath']('"+
a+"') threw an exception: "+h.message)}b.f.unlink(b,c);d.Ca(e);try{if(d.s.onDeletePath)d.s.onDeletePath(a)}catch(h){F("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+h.message)}},readlink:function(a){a=d.h(a).node;if(!a)throw new d.b(44);if(!a.f.readlink)throw new d.b(28);return P.resolve(d.I(a.parent),a.f.readlink(a))},stat:function(a,b){a=d.h(a,{H:!b}).node;if(!a)throw new d.b(44);if(!a.f.D)throw new d.b(63);return a.f.D(a)},lstat:function(a){return d.stat(a,!0)},chmod:function(a,
b,c){var e;"string"===typeof a?e=d.h(a,{H:!c}).node:e=a;if(!e.f.o)throw new d.b(63);e.f.o(e,{mode:b&4095|e.mode&-4096,timestamp:Date.now()})},lchmod:function(a,b){d.chmod(a,b,!0)},fchmod:function(a,b){a=d.P(a);if(!a)throw new d.b(8);d.chmod(a.node,b)},chown:function(a,b,c,e){var g;"string"===typeof a?g=d.h(a,{H:!e}).node:g=a;if(!g.f.o)throw new d.b(63);g.f.o(g,{timestamp:Date.now()})},lchown:function(a,b,c){d.chown(a,b,c,!0)},fchown:function(a,b,c){a=d.P(a);if(!a)throw new d.b(8);d.chown(a.node,b,
c)},truncate:function(a,b){if(0>b)throw new d.b(28);var c;"string"===typeof a?c=d.h(a,{H:!0}).node:c=a;if(!c.f.o)throw new d.b(63);if(d.m(c.mode))throw new d.b(31);if(!d.isFile(c.mode))throw new d.b(28);if(a=d.S(c,"w"))throw new d.b(a);c.f.o(c,{size:b,timestamp:Date.now()})},Te:function(a,b){a=d.P(a);if(!a)throw new d.b(8);if(0===(a.flags&2097155))throw new d.b(28);d.truncate(a.node,b)},jf:function(a,b,c){a=d.h(a,{H:!0}).node;a.f.o(a,{timestamp:Math.max(b,c)})},open:function(a,b,c,e,g){if(""===a)throw new d.b(44);
b="string"===typeof b?d.Yb(b):b;c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var h=a;else{a=w.normalize(a);try{h=d.h(a,{H:!(b&131072)}).node}catch(n){}}var l=!1;if(b&64)if(h){if(b&128)throw new d.b(20);}else h=d.F(a,c,0),l=!0;if(!h)throw new d.b(44);d.ja(h.mode)&&(b&=-513);if(b&65536&&!d.m(h.mode))throw new d.b(54);if(!l&&(c=d.Xb(h,b)))throw new d.b(c);b&512&&d.truncate(h,0);b&=-131713;e=d.Lb({node:h,path:d.I(h),flags:b,seekable:!0,position:0,g:h.g,mc:[],error:!1},e,g);
e.g.open&&e.g.open(e);!f.logReadFiles||b&1||(d.Pa||(d.Pa={}),a in d.Pa||(d.Pa[a]=1,F("FS.trackingDelegate error on read file: "+a)));try{d.s.onOpenFile&&(g=0,1!==(b&2097155)&&(g|=d.sb.pb.xb),0!==(b&2097155)&&(g|=d.sb.pb.yb),d.s.onOpenFile(a,g))}catch(n){F("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+n.message)}return e},close:function(a){if(d.ka(a))throw new d.b(8);a.V&&(a.V=null);try{a.g.close&&a.g.close(a)}catch(b){throw b;}finally{d.Fb(a.fd)}a.fd=null},ka:function(a){return null===
a.fd},A:function(a,b,c){if(d.ka(a))throw new d.b(8);if(!a.seekable||!a.g.A)throw new d.b(70);if(0!=c&&1!=c&&2!=c)throw new d.b(28);a.position=a.g.A(a,b,c);a.mc=[];return a.position},read:function(a,b,c,e,g){if(0>e||0>g)throw new d.b(28);if(d.ka(a))throw new d.b(8);if(1===(a.flags&2097155))throw new d.b(8);if(d.m(a.node.mode))throw new d.b(31);if(!a.g.read)throw new d.b(28);var h="undefined"!==typeof g;if(!h)g=a.position;else if(!a.seekable)throw new d.b(70);b=a.g.read(a,b,c,e,g);h||(a.position+=b);
return b},write:function(a,b,c,e,g,h){if(0>e||0>g)throw new d.b(28);if(d.ka(a))throw new d.b(8);if(0===(a.flags&2097155))throw new d.b(8);if(d.m(a.node.mode))throw new d.b(31);if(!a.g.write)throw new d.b(28);a.seekable&&a.flags&1024&&d.A(a,0,2);var l="undefined"!==typeof g;if(!l)g=a.position;else if(!a.seekable)throw new d.b(70);b=a.g.write(a,b,c,e,g,h);l||(a.position+=b);try{if(a.path&&d.s.onWriteToFile)d.s.onWriteToFile(a.path)}catch(n){F("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+
n.message)}return b},ia:function(a,b,c){if(d.ka(a))throw new d.b(8);if(0>b||0>=c)throw new d.b(28);if(0===(a.flags&2097155))throw new d.b(8);if(!d.isFile(a.node.mode)&&!d.m(a.node.mode))throw new d.b(43);if(!a.g.ia)throw new d.b(138);a.g.ia(a,b,c)},aa:function(a,b,c,e,g,h,l){if(0!==(h&2)&&0===(l&2)&&2!==(a.flags&2097155))throw new d.b(2);if(1===(a.flags&2097155))throw new d.b(2);if(!a.g.aa)throw new d.b(43);return a.g.aa(a,b,c,e,g,h,l)},Z:function(a,b,c,e,g){return a&&a.g.Z?a.g.Z(a,b,c,e,g):0},cf:function(){return 0},
Ia:function(a,b,c){if(!a.g.Ia)throw new d.b(59);return a.g.Ia(a,b,c)},readFile:function(a,b){b=b||{};b.flags=b.flags||"r";b.encoding=b.encoding||"binary";if("utf8"!==b.encoding&&"binary"!==b.encoding)throw Error('Invalid encoding type "'+b.encoding+'"');var c,e=d.open(a,b.flags);a=d.stat(a).size;var g=new Uint8Array(a);d.read(e,g,0,a,0);"utf8"===b.encoding?c=R(g,0):"binary"===b.encoding&&(c=g);d.close(e);return c},writeFile:function(a,b,c){c=c||{};c.flags=c.flags||"w";a=d.open(a,c.flags,c.mode);if("string"===
typeof b){var e=new Uint8Array(ia(b)+1);b=W(b,e,0,e.length);d.write(a,e,0,b,void 0,c.Db)}else if(ArrayBuffer.isView(b))d.write(a,b,0,b.byteLength,void 0,c.Db);else throw Error("Unsupported data type");d.close(a)},cwd:function(){return d.$a},chdir:function(a){a=d.h(a,{H:!0});if(null===a.node)throw new d.b(44);if(!d.m(a.node.mode))throw new d.b(54);var b=d.S(a.node,"x");if(b)throw new d.b(b);d.$a=a.path},Hb:function(){d.mkdir("/tmp");d.mkdir("/home");d.mkdir("/home/web_user")},Gb:function(){d.mkdir("/dev");
d.Sa(d.Y(1,3),{read:function(){return 0},write:function(e,g,h,l){return l}});d.sa("/dev/null",d.Y(1,3));T.register(d.Y(5,0),T.Nb);T.register(d.Y(6,0),T.Mb);d.sa("/dev/tty",d.Y(5,0));d.sa("/dev/tty1",d.Y(6,0));if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(S)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(e){}b||(b=function(){B("random_device")});d.O("/dev","random",
b);d.O("/dev","urandom",b);d.mkdir("/dev/shm");d.mkdir("/dev/shm/tmp")},Jb:function(){d.mkdir("/proc");d.mkdir("/proc/self");d.mkdir("/proc/self/fd");d.i({i:function(){var a=d.createNode("/proc/self","fd",16895,73);a.f={lookup:function(b,c){var e=d.P(+c);if(!e)throw new d.b(8);b={parent:null,i:{ob:"fake"},f:{readlink:function(){return e.path}}};return b.parent=b}};return a}},{},"/proc/self/fd")},Kb:function(){f.stdin?d.O("/dev","stdin",f.stdin):d.symlink("/dev/tty","/dev/stdin");f.stdout?d.O("/dev",
"stdout",null,f.stdout):d.symlink("/dev/tty","/dev/stdout");f.stderr?d.O("/dev","stderr",null,f.stderr):d.symlink("/dev/tty1","/dev/stderr");d.open("/dev/stdin","r");d.open("/dev/stdout","w");d.open("/dev/stderr","w")},bb:function(){d.b||(d.b=function(a,b){this.node=b;this.hc=function(c){this.l=c};this.hc(a);this.message="FS error"},d.b.prototype=Error(),d.b.prototype.constructor=d.b,[44].forEach(function(a){d.Fa[a]=new d.b(a);d.Fa[a].stack="<generic error, no stack>"}))},Ta:function(){d.bb();d.L=
Array(4096);d.i(v,{},"/");d.Hb();d.Gb();d.Jb();d.eb={MEMFS:v,NODEFS:u,WORKERFS:G}},W:function(a,b,c){d.W.Ha=!0;d.bb();f.stdin=a||f.stdin;f.stdout=b||f.stdout;f.stderr=c||f.stderr;d.Kb()},quit:function(){d.W.Ha=!1;var a=f._fflush;a&&a(0);for(a=0;a<d.streams.length;a++){var b=d.streams[a];b&&d.close(b)}},T:function(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c},Ye:function(a,b){a=w.join.apply(null,a);b&&"/"==a[0]&&(a=a.substr(1));return a},Ee:function(a,b){return P.resolve(b,a)},ff:function(a){return w.normalize(a)},
Se:function(a,b){a=d.Aa(a,b);if(a.exists)return a.object;Y(a.error);return null},Aa:function(a,b){try{var c=d.h(a,{H:!b});a=c.path}catch(g){}var e={pa:!1,exists:!1,error:0,name:null,path:null,object:null,ac:!1,cc:null,bc:null};try{c=d.h(a,{parent:!0}),e.ac=!0,e.cc=c.path,e.bc=c.node,e.name=w.basename(a),c=d.h(a,{H:!b}),e.exists=!0,e.path=c.path,e.object=c.node,e.name=c.node.name,e.pa="/"===c.path}catch(g){e.error=g.l}return e},He:function(a,b,c,e){a=w.v("string"===typeof a?a:d.I(a),b);c=d.T(c,e);
return d.mkdir(a,c)},Ke:function(a,b){a="string"===typeof a?a:d.I(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var e=w.v(a,c);try{d.mkdir(e)}catch(g){}a=e}}return e},Ib:function(a,b,c,e,g){a=w.v("string"===typeof a?a:d.I(a),b);e=d.T(e,g);return d.create(a,e)},Za:function(a,b,c,e,g,h){a=b?w.v("string"===typeof a?a:d.I(a),b):a;e=d.T(e,g);g=d.create(a,e);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var l=c.length;b<l;++b)a[b]=c.charCodeAt(b);c=a}d.chmod(g,e|146);a=d.open(g,
"w");d.write(a,c,0,c.length,0,h);d.close(a);d.chmod(g,e)}return g},O:function(a,b,c,e){a=w.v("string"===typeof a?a:d.I(a),b);b=d.T(!!c,!!e);d.O.La||(d.O.La=64);var g=d.Y(d.O.La++,0);d.Sa(g,{open:function(h){h.seekable=!1},close:function(){e&&e.buffer&&e.buffer.length&&e(10)},read:function(h,l,n,t){for(var p=0,q=0;q<t;q++){try{var A=c()}catch(D){throw new d.b(29);}if(void 0===A&&0===p)throw new d.b(6);if(null===A||void 0===A)break;p++;l[n+q]=A}p&&(h.node.timestamp=Date.now());return p},write:function(h,
l,n,t){for(var p=0;p<t;p++)try{e(l[n+p])}catch(q){throw new d.b(29);}t&&(h.node.timestamp=Date.now());return p}});return d.sa(a,b,g)},Je:function(a,b,c){a=w.v("string"===typeof a?a:d.I(a),b);return d.symlink(c,a)},hb:function(a){if(a.Ja||a.Vb||a.link||a.c)return!0;var b=!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");
if(pa)try{a.c=Da(pa(a.url),!0),a.j=a.c.length}catch(c){b=!1}else throw Error("Cannot load without read() or XMLHttpRequest.");b||Y(29);return b},Ie:function(a,b,c,e,g){function h(){this.Ka=!1;this.B=[]}h.prototype.get=function(p){if(!(p>this.length-1||0>p)){var q=p%this.chunkSize;return this.kb(p/this.chunkSize|0)[q]}};h.prototype.Cb=function(p){this.kb=p};h.prototype.Xa=function(){var p=new XMLHttpRequest;p.open("HEAD",c,!1);p.send(null);if(!(200<=p.status&&300>p.status||304===p.status))throw Error("Couldn't load "+
c+". Status: "+p.status);var q=Number(p.getResponseHeader("Content-length")),A,D=(A=p.getResponseHeader("Accept-Ranges"))&&"bytes"===A;p=(A=p.getResponseHeader("Content-Encoding"))&&"gzip"===A;var k=1048576;D||(k=q);var r=this;r.Cb(function(y){var E=y*k,L=(y+1)*k-1;L=Math.min(L,q-1);if("undefined"===typeof r.B[y]){var Va=r.B;if(E>L)throw Error("invalid range ("+E+", "+L+") or no bytes requested!");if(L>q-1)throw Error("only "+q+" bytes available! programmer error!");var C=new XMLHttpRequest;C.open("GET",
c,!1);q!==k&&C.setRequestHeader("Range","bytes="+E+"-"+L);"undefined"!=typeof Uint8Array&&(C.responseType="arraybuffer");C.overrideMimeType&&C.overrideMimeType("text/plain; charset=x-user-defined");C.send(null);if(!(200<=C.status&&300>C.status||304===C.status))throw Error("Couldn't load "+c+". Status: "+C.status);E=void 0!==C.response?new Uint8Array(C.response||[]):Da(C.responseText||"",!0);Va[y]=E}if("undefined"===typeof r.B[y])throw Error("doXHR failed!");return r.B[y]});if(p||!q)k=q=1,k=q=this.kb(0).length,
ca("LazyFiles on gzip forces download of the whole file when length is accessed");this.Ab=q;this.zb=k;this.Ka=!0};if("undefined"!==typeof XMLHttpRequest){if(!Q)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var l=new h;Object.defineProperties(l,{length:{get:function(){this.Ka||this.Xa();return this.Ab}},chunkSize:{get:function(){this.Ka||this.Xa();return this.zb}}});l={Ja:!1,c:l}}else l={Ja:!1,url:c};var n=d.Ib(a,b,l,e,g);
l.c?n.c=l.c:l.url&&(n.c=null,n.url=l.url);Object.defineProperties(n,{j:{get:function(){return this.c.length}}});var t={};Object.keys(n.g).forEach(function(p){var q=n.g[p];t[p]=function(){if(!d.hb(n))throw new d.b(29);return q.apply(null,arguments)}});t.read=function(p,q,A,D,k){if(!d.hb(n))throw new d.b(29);p=p.node.c;if(k>=p.length)return 0;D=Math.min(p.length-k,D);if(p.slice)for(var r=0;r<D;r++)q[A+r]=p[k+r];else for(r=0;r<D;r++)q[A+r]=p.get(k+r);return D};n.g=t;return n},Le:function(a,b,c,e,g,h,
l,n,t,p){function q(k){function r(E){p&&p();n||d.Za(a,b,E,e,g,t);h&&h();Ka(D)}var y=!1;f.preloadPlugins.forEach(function(E){!y&&E.canHandle(A)&&(E.handle(k,A,r,function(){l&&l();Ka(D)}),y=!0)});y||r(k)}ub.W();var A=b?P.resolve(w.v(a,b)):a,D="cp "+A;cb(D);"string"==typeof c?ub.Fe(c,function(k){q(k)},l):q(c)},indexedDB:function(){return window.indexedDB||window.mozIndexedDB||window.webkitIndexedDB||window.msIndexedDB},Ua:function(){return"EM_FS_"+window.location.pathname},Va:20,ga:"FILE_DATA",df:function(a,
b,c){b=b||function(){};c=c||function(){};var e=d.indexedDB();try{var g=e.open(d.Ua(),d.Va)}catch(h){return c(h)}g.onupgradeneeded=function(){ca("creating db");g.result.createObjectStore(d.ga)};g.onsuccess=function(){var h=g.result.transaction([d.ga],"readwrite"),l=h.objectStore(d.ga),n=0,t=0,p=a.length;a.forEach(function(q){q=l.put(d.Aa(q).object.c,q);q.onsuccess=function(){n++;n+t==p&&(0==t?b():c())};q.onerror=function(){t++;n+t==p&&(0==t?b():c())}});h.onerror=c};g.onerror=c},Ze:function(a,b,c){b=
b||function(){};c=c||function(){};var e=d.indexedDB();try{var g=e.open(d.Ua(),d.Va)}catch(h){return c(h)}g.onupgradeneeded=c;g.onsuccess=function(){var h=g.result;try{var l=h.transaction([d.ga],"readonly")}catch(A){c(A);return}var n=l.objectStore(d.ga),t=0,p=0,q=a.length;a.forEach(function(A){var D=n.get(A);D.onsuccess=function(){d.Aa(A).exists&&d.unlink(A);d.Za(w.dirname(A),w.basename(A),D.result,!0,!0,!0);t++;t+p==q&&(0==p?b():c())};D.onerror=function(){p++;t+p==q&&(0==p?b():c())}});l.onerror=c};
g.onerror=c}},x={$e:{},ub:5,umask:511,Ge:function(a,b){if("/"!==b[0]){if(-100===a)a=d.cwd();else{a=d.P(a);if(!a)throw new d.b(8);a=a.path}b=w.v(a,b)}return b},Da:function(a,b,c){try{var e=a(b)}catch(g){if(g&&g.node&&w.normalize(b)!==w.normalize(d.I(g.node)))return-54;throw g;}m[c>>2]=e.dev;m[c+4>>2]=0;m[c+8>>2]=e.ino;m[c+12>>2]=e.mode;m[c+16>>2]=e.nlink;m[c+20>>2]=e.uid;m[c+24>>2]=e.gid;m[c+28>>2]=e.rdev;m[c+32>>2]=0;J=[e.size>>>0,(z=e.size,1<=+ra(z)?0<z?(sa(+aa(z/4294967296),4294967295)|0)>>>0:~~+Z((z-
+(~~z>>>0))/4294967296)>>>0:0)];m[c+40>>2]=J[0];m[c+44>>2]=J[1];m[c+48>>2]=4096;m[c+52>>2]=e.blocks;m[c+56>>2]=e.atime.getTime()/1E3|0;m[c+60>>2]=0;m[c+64>>2]=e.mtime.getTime()/1E3|0;m[c+68>>2]=0;m[c+72>>2]=e.ctime.getTime()/1E3|0;m[c+76>>2]=0;J=[e.ino>>>0,(z=e.ino,1<=+ra(z)?0<z?(sa(+aa(z/4294967296),4294967295)|0)>>>0:~~+Z((z-+(~~z>>>0))/4294967296)>>>0:0)];m[c+80>>2]=J[0];m[c+84>>2]=J[1];return 0},Qe:function(a,b,c,e,g){a=V.slice(a,a+c);d.Z(b,a,g,c,e)},Oe:function(a,b){a=w.normalize(a);"/"===a[a.length-
1]&&(a=a.substr(0,a.length-1));d.mkdir(a,b,0);return 0},Pe:function(a,b,c){switch(b&61440){case 32768:case 8192:case 24576:case 4096:case 49152:break;default:return-28}d.F(a,b,c);return 0},Re:function(a,b,c){if(0>=c)return-28;a=d.readlink(a);var e=Math.min(c,ia(a)),g=I[b+e];W(a,V,b,c+1);I[b+e]=g;return e},Me:function(a,b){if(b&-8)return-28;a=d.h(a,{H:!0}).node;if(!a)return-44;var c="";b&4&&(c+="r");b&2&&(c+="w");b&1&&(c+="x");return c&&d.S(a,c)?-2:0},Ne:function(a,b,c){var e=d.P(c);e&&d.close(e);
return d.open(a,b,0,c,c).fd},Ob:function(a,b,c,e){for(var g=0,h=0;h<c;h++){var l=m[b+(8*h+4)>>2],n=d.read(a,I,m[b+8*h>>2],l,e);if(0>n)return-1;g+=n;if(n<l)break}return g},Pb:function(a,b,c,e){for(var g=0,h=0;h<c;h++){var l=d.write(a,I,m[b+8*h>>2],m[b+(8*h+4)>>2],e);if(0>l)return-1;g+=l}return g},fa:void 0,get:function(){x.fa+=4;return m[x.fa-4>>2]},U:function(a){return ba(a)},J:function(a){a=d.P(a);if(!a)throw new d.b(8);return a},Ue:function(a){return a}},ea;S?ea=function(){var a=process.hrtime();
return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?ea=dateNow:ea=function(){return performance.now()};var gb={},Ab=(W("GMT",V,2334240,4),2334240),Ba=[31,29,31,30,31,30,31,31,30,31,30,31],Ca=[31,28,31,30,31,30,31,31,30,31,30,31];Object.defineProperties(Xa.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Vb:{get:function(){return d.m(this.mode)}},
Ja:{get:function(){return d.ja(this.mode)}}});d.vb=Xa;d.Ta();var ub;if(S){var H=require("fs"),tb=require("path");u.Ta()}var vb={__assert_fail:function(a,b,c,e){B("Assertion failed: "+ba(a)+", at: "+[b?ba(b):"unknown filename",c,e?ba(e):"unknown function"])},__sys__newselect:function(a,b,c,e){for(var g=0,h=b?m[b>>2]:0,l=b?m[b+4>>2]:0,n=c?m[c>>2]:0,t=c?m[c+4>>2]:0,p=e?m[e>>2]:0,q=e?m[e+4>>2]:0,A=0,D=0,k=0,r=0,y=0,E=0,L=(b?m[b>>2]:0)|(c?m[c>>2]:0)|(e?m[e>>2]:0),Va=(b?m[b+4>>2]:0)|(c?m[c+4>>2]:0)|(e?
m[e+4>>2]:0),C=0;C<a;C++){var K=1<<C%32;if(32>C?L&K:Va&K){var Ha=d.P(C);if(!Ha)throw new d.b(8);var Ia=x.ub;Ha.g.dc&&(Ia=Ha.g.dc(Ha));Ia&1&&(32>C?h&K:l&K)&&(32>C?A|=K:D|=K,g++);Ia&4&&(32>C?n&K:t&K)&&(32>C?k|=K:r|=K,g++);Ia&2&&(32>C?p&K:q&K)&&(32>C?y|=K:E|=K,g++)}}b&&(m[b>>2]=A,m[b+4>>2]=D);c&&(m[c>>2]=k,m[c+4>>2]=r);e&&(m[e>>2]=y,m[e+4>>2]=E);return g},__sys_fcntl64:function(a,b,c){x.fa=c;try{var e=x.J(a);switch(b){case 0:var g=x.get();return 0>g?-28:d.open(e.path,e.flags,0,g).fd;case 1:case 2:return 0;
case 3:return e.flags;case 4:return g=x.get(),e.flags|=g,0;case 12:return g=x.get(),Sa[g+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return Y(28),-1;default:return-28}}catch(h){return"undefined"!==typeof d&&h instanceof d.b||B(h),-h.l}},__sys_fstat64:function(a,b){try{var c=x.J(a);return x.Da(d.stat,c.path,b)}catch(e){return"undefined"!==typeof d&&e instanceof d.b||B(e),-e.l}},__sys_getdents64:function(a,b,c){try{var e=x.J(a);e.V||(e.V=d.readdir(e.path));a=0;for(var g=d.A(e,
0,1),h=Math.floor(g/280);h<e.V.length&&a+280<=c;){var l=e.V[h];if("."===l[0]){var n=1;var t=4}else{var p=d.K(e.node,l);n=p.id;t=d.ja(p.mode)?2:d.m(p.mode)?4:d.R(p.mode)?10:8}J=[n>>>0,(z=n,1<=+ra(z)?0<z?(sa(+aa(z/4294967296),4294967295)|0)>>>0:~~+Z((z-+(~~z>>>0))/4294967296)>>>0:0)];m[b+a>>2]=J[0];m[b+a+4>>2]=J[1];J=[280*(h+1)>>>0,(z=280*(h+1),1<=+ra(z)?0<z?(sa(+aa(z/4294967296),4294967295)|0)>>>0:~~+Z((z-+(~~z>>>0))/4294967296)>>>0:0)];m[b+a+8>>2]=J[0];m[b+a+12>>2]=J[1];Sa[b+a+16>>1]=280;I[b+a+18>>
0]=t;W(l,V,b+a+19,256);a+=280;h+=1}d.A(e,280*h,0);return a}catch(q){return"undefined"!==typeof d&&q instanceof d.b||B(q),-q.l}},__sys_ioctl:function(a,b,c){x.fa=c;try{var e=x.J(a);switch(b){case 21509:case 21505:return e.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return e.tty?0:-59;case 21519:if(!e.tty)return-59;var g=x.get();return m[g>>2]=0;case 21520:return e.tty?-28:-59;case 21531:return g=x.get(),d.Ia(e,b,g);case 21523:return e.tty?0:-59;case 21524:return e.tty?
0:-59;default:B("bad ioctl syscall "+b)}}catch(h){return"undefined"!==typeof d&&h instanceof d.b||B(h),-h.l}},__sys_lstat64:function(a,b){try{return a=x.U(a),x.Da(d.lstat,a,b)}catch(c){return"undefined"!==typeof d&&c instanceof d.b||B(c),-c.l}},__sys_madvise1:function(){return 0},__sys_open:function(a,b,c){x.fa=c;try{var e=x.U(a),g=x.get();return d.open(e,b,g).fd}catch(h){return"undefined"!==typeof d&&h instanceof d.b||B(h),-h.l}},__sys_read:function(a,b,c){try{var e=x.J(a);return d.read(e,I,b,c)}catch(g){return"undefined"!==
typeof d&&g instanceof d.b||B(g),-g.l}},__sys_rename:function(a,b){try{return a=x.U(a),b=x.U(b),d.rename(a,b),0}catch(c){return"undefined"!==typeof d&&c instanceof d.b||B(c),-c.l}},__sys_rmdir:function(a){try{return a=x.U(a),d.rmdir(a),0}catch(b){return"undefined"!==typeof d&&b instanceof d.b||B(b),-b.l}},__sys_stat64:function(a,b){try{return a=x.U(a),x.Da(d.stat,a,b)}catch(c){return"undefined"!==typeof d&&c instanceof d.b||B(c),-c.l}},__sys_unlink:function(a){try{return a=x.U(a),d.unlink(a),0}catch(b){return"undefined"!==
typeof d&&b instanceof d.b||B(b),-b.l}},abort:function(){B()},clock:wa,clock_gettime:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=ea();else return Y(28),-1;m[b>>2]=a/1E3|0;m[b+4>>2]=a%1E3*1E6|0;return 0},emscripten_get_sbrk_ptr:function(){return 2334176},emscripten_memcpy_big:function(a,b,c){V.copyWithin(a,b,b+c)},emscripten_resize_heap:function(){B("OOM")},environ_get:function(a,b){var c=0;ma().forEach(function(e,g){var h=b+c;g=m[a+4*g>>2]=h;for(h=0;h<e.length;++h)I[g++>>0]=e.charCodeAt(h);
I[g>>0]=0;c+=e.length+1});return 0},environ_sizes_get:function(a,b){var c=ma();m[a>>2]=c.length;var e=0;c.forEach(function(g){e+=g.length+1});m[b>>2]=e;return 0},exit:function(a){nb(a)},fd_close:function(a){try{var b=x.J(a);d.close(b);return 0}catch(c){return"undefined"!==typeof d&&c instanceof d.b||B(c),c.l}},fd_fdstat_get:function(a,b){try{var c=x.J(a);I[b>>0]=c.tty?2:d.m(c.mode)?3:d.R(c.mode)?7:4;return 0}catch(e){return"undefined"!==typeof d&&e instanceof d.b||B(e),e.l}},fd_read:function(a,b,
c,e){try{var g=x.J(a),h=x.Ob(g,b,c);m[e>>2]=h;return 0}catch(l){return"undefined"!==typeof d&&l instanceof d.b||B(l),l.l}},fd_seek:function(a,b,c,e,g){try{var h=x.J(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;d.A(h,a,e);J=[h.position>>>0,(z=h.position,1<=+ra(z)?0<z?(sa(+aa(z/4294967296),4294967295)|0)>>>0:~~+Z((z-+(~~z>>>0))/4294967296)>>>0:0)];m[g>>2]=J[0];m[g+4>>2]=J[1];h.V&&0===a&&0===e&&(h.V=null);return 0}catch(l){return"undefined"!==typeof d&&l instanceof
d.b||B(l),l.l}},fd_write:function(a,b,c,e){try{var g=x.J(a),h=x.Pb(g,b,c);m[e>>2]=h;return 0}catch(l){return"undefined"!==typeof d&&l instanceof d.b||B(l),l.l}},gmtime:function(a){return hb(a,2334192)},gmtime_r:hb,localtime:function(a){return kb(a,2334192)},localtime_r:kb,memory:qa,mktime:function(a){ya();var b=new Date(m[a+20>>2]+1900,m[a+16>>2],m[a+12>>2],m[a+8>>2],m[a+4>>2],m[a>>2],0),c=m[a+32>>2],e=b.getTimezoneOffset(),g=new Date(b.getFullYear(),0,1),h=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),
l=g.getTimezoneOffset(),n=Math.min(l,h);0>c?m[a+32>>2]=Number(h!=l&&n==e):0<c!=(n==e)&&(h=Math.max(l,h),b.setTime(b.getTime()+6E4*((0<c?n:h)-e)));m[a+24>>2]=b.getDay();m[a+28>>2]=(b.getTime()-g.getTime())/864E5|0;return b.getTime()/1E3|0},nanosleep:function(a,b){if(0===a)return Y(28),-1;var c=m[a>>2];a=m[a+4>>2];if(0>a||999999999<a||0>c)return Y(28),-1;0!==b&&(m[b>>2]=0,m[b+4>>2]=0);b=1E6*c+a/1E3;for(c=ea();ea()-c<b/1E3;);},round:function(a){a=+a;return 0<=a?+aa(a+.5):+Z(a-.5)},roundf:function(a){a=
+a;return 0<=a?+aa(a+.5):+Z(a-.5)},setTempRet0:function(){},signal:function(){return 0},strftime:function(a,b,c,e){function g(k,r,y){for(k="number"===typeof k?k.toString():k||"";k.length<r;)k=y[0]+k;return k}function h(k,r){return g(k,r,"0")}function l(k,r){function y(L){return 0>L?-1:0<L?1:0}var E;0===(E=y(k.getFullYear()-r.getFullYear()))&&0===(E=y(k.getMonth()-r.getMonth()))&&(E=y(k.getDate()-r.getDate()));return E}function n(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-1,11,29);
case 1:return k;case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),0,2);case 4:return new Date(k.getFullYear(),0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-1,11,30)}}function t(k){k=Aa(new Date(k.C+1900,0,1),k.wa);var r=new Date(k.getFullYear()+1,0,4),y=n(new Date(k.getFullYear(),0,4));r=n(r);return 0>=l(y,k)?0>=l(r,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var p=m[e+40>>2];e={kc:m[e>>2],jc:m[e+4>>2],ua:m[e+
8>>2],oa:m[e+12>>2],ea:m[e+16>>2],C:m[e+20>>2],va:m[e+24>>2],wa:m[e+28>>2],gf:m[e+32>>2],ic:m[e+36>>2],lc:p?ba(p):""};c=ba(c);p={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};
for(var q in p)c=c.replace(new RegExp(q,"g"),p[q]);var A="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),D="January February March April May June July August September October November December".split(" ");p={"%a":function(k){return A[k.va].substring(0,3)},"%A":function(k){return A[k.va]},"%b":function(k){return D[k.ea].substring(0,3)},"%B":function(k){return D[k.ea]},"%C":function(k){return h((k.C+1900)/100|0,2)},"%d":function(k){return h(k.oa,2)},"%e":function(k){return g(k.oa,
2," ")},"%g":function(k){return t(k).toString().substring(2)},"%G":function(k){return t(k)},"%H":function(k){return h(k.ua,2)},"%I":function(k){k=k.ua;0==k?k=12:12<k&&(k-=12);return h(k,2)},"%j":function(k){return h(k.oa+Oa(za(k.C+1900)?Ba:Ca,k.ea-1),3)},"%m":function(k){return h(k.ea+1,2)},"%M":function(k){return h(k.jc,2)},"%n":function(){return"\n"},"%p":function(k){return 0<=k.ua&&12>k.ua?"AM":"PM"},"%S":function(k){return h(k.kc,2)},"%t":function(){return"\t"},"%u":function(k){return k.va||7},
"%U":function(k){var r=new Date(k.C+1900,0,1),y=0===r.getDay()?r:Aa(r,7-r.getDay());k=new Date(k.C+1900,k.ea,k.oa);return 0>l(y,k)?(r=Oa(za(k.getFullYear())?Ba:Ca,k.getMonth()-1)-31,h(Math.ceil((31-y.getDate()+r+k.getDate())/7),2)):0===l(y,r)?"01":"00"},"%V":function(k){var r=new Date(k.C+1901,0,4),y=n(new Date(k.C+1900,0,4));r=n(r);var E=Aa(new Date(k.C+1900,0,1),k.wa);return 0>l(E,y)?"53":0>=l(r,E)?"01":h(Math.ceil((y.getFullYear()<k.C+1900?k.wa+32-y.getDate():k.wa+1-y.getDate())/7),2)},"%w":function(k){return k.va},
"%W":function(k){var r=new Date(k.C,0,1),y=1===r.getDay()?r:Aa(r,0===r.getDay()?1:7-r.getDay()+1);k=new Date(k.C+1900,k.ea,k.oa);return 0>l(y,k)?(r=Oa(za(k.getFullYear())?Ba:Ca,k.getMonth()-1)-31,h(Math.ceil((31-y.getDate()+r+k.getDate())/7),2)):0===l(y,r)?"01":"00"},"%y":function(k){return(k.C+1900).toString().substring(2)},"%Y":function(k){return k.C+1900},"%z":function(k){k=k.ic;var r=0<=k;k=Math.abs(k)/60;return(r?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":function(k){return k.lc},
"%%":function(){return"%"}};for(q in p)0<=c.indexOf(q)&&(c=c.replace(new RegExp(q,"g"),p[q](e)));q=Da(c,!1);if(q.length>b)return 0;I.set(q,a);return q.length-1},table:Eb,time:function(a){var b=Date.now()/1E3|0;a&&(m[a>>2]=b);return b}},wb=function(){function a(g){f.asm=g.exports;Ka("wasm-instantiate")}function b(g){a(g.instance)}function c(g){return yb().then(function(h){return WebAssembly.instantiate(h,e)}).then(g,function(h){F("failed to asynchronously prepare wasm: "+h);B(h)})}var e={env:vb,wasi_snapshot_preview1:vb};
cb("wasm-instantiate");if(f.instantiateWasm)try{return f.instantiateWasm(e,a)}catch(g){return F("Module.instantiateWasm callback failed with error: "+g),!1}(function(){if(la||"function"!==typeof WebAssembly.instantiateStreaming||db(O)||Na(O,"file://")||"function"!==typeof fetch)return c(b);fetch(O,{credentials:"same-origin"}).then(function(g){return WebAssembly.instantiateStreaming(g,e).then(b,function(h){F("wasm streaming compile failed: "+h);F("falling back to ArrayBuffer instantiation");c(b)})})})();
return{}}();f.asm=wb;var sb=f.___wasm_call_ctors=function(){return(sb=f.___wasm_call_ctors=f.asm.__wasm_call_ctors).apply(null,arguments)},fb=f.___errno_location=function(){return(fb=f.___errno_location=f.asm.__errno_location).apply(null,arguments)};f._fflush=function(){return(f._fflush=f.asm.fflush).apply(null,arguments)};f._main=function(){return(f._main=f.asm.main).apply(null,arguments)};f._free=function(){return(f._free=f.asm.free).apply(null,arguments)};var ta=f._malloc=function(){return(ta=
f._malloc=f.asm.malloc).apply(null,arguments)},da=f.__get_tzname=function(){return(da=f.__get_tzname=f.asm._get_tzname).apply(null,arguments)},jb=f.__get_daylight=function(){return(jb=f.__get_daylight=f.asm._get_daylight).apply(null,arguments)},ib=f.__get_timezone=function(){return(ib=f.__get_timezone=f.asm._get_timezone).apply(null,arguments)};f.stackSave=function(){return(f.stackSave=f.asm.stackSave).apply(null,arguments)};var Ja=f.stackAlloc=function(){return(Ja=f.stackAlloc=f.asm.stackAlloc).apply(null,
arguments)};f.stackRestore=function(){return(f.stackRestore=f.asm.stackRestore).apply(null,arguments)};f.__growWasmMemory=function(){return(f.__growWasmMemory=f.asm.__growWasmMemory).apply(null,arguments)};f.dynCall_iii=function(){return(f.dynCall_iii=f.asm.dynCall_iii).apply(null,arguments)};f.dynCall_viiii=function(){return(f.dynCall_viiii=f.asm.dynCall_viiii).apply(null,arguments)};f.dynCall_vi=function(){return(f.dynCall_vi=f.asm.dynCall_vi).apply(null,arguments)};f.dynCall_iiii=function(){return(f.dynCall_iiii=
f.asm.dynCall_iiii).apply(null,arguments)};f.dynCall_ii=function(){return(f.dynCall_ii=f.asm.dynCall_ii).apply(null,arguments)};f.dynCall_iiiiii=function(){return(f.dynCall_iiiiii=f.asm.dynCall_iiiiii).apply(null,arguments)};f.dynCall_iiiii=function(){return(f.dynCall_iiiii=f.asm.dynCall_iiiii).apply(null,arguments)};f.dynCall_iiiiiiiii=function(){return(f.dynCall_iiiiiiiii=f.asm.dynCall_iiiiiiiii).apply(null,arguments)};f.dynCall_vii=function(){return(f.dynCall_vii=f.asm.dynCall_vii).apply(null,
arguments)};f.dynCall_jiji=function(){return(f.dynCall_jiji=f.asm.dynCall_jiji).apply(null,arguments)};f.dynCall_jiiji=function(){return(f.dynCall_jiiji=f.asm.dynCall_jiiji).apply(null,arguments)};f.dynCall_viiiiiiff=function(){return(f.dynCall_viiiiiiff=f.asm.dynCall_viiiiiiff).apply(null,arguments)};f.dynCall_viii=function(){return(f.dynCall_viii=f.asm.dynCall_viii).apply(null,arguments)};f.dynCall_viiiii=function(){return(f.dynCall_viiiii=f.asm.dynCall_viiiii).apply(null,arguments)};f.dynCall_viiiiiifi=
function(){return(f.dynCall_viiiiiifi=f.asm.dynCall_viiiiiifi).apply(null,arguments)};f.dynCall_iiiiiii=function(){return(f.dynCall_iiiiiii=f.asm.dynCall_iiiiiii).apply(null,arguments)};f.dynCall_viiiiii=function(){return(f.dynCall_viiiiii=f.asm.dynCall_viiiiii).apply(null,arguments)};f.dynCall_viiiiiiiii=function(){return(f.dynCall_viiiiiiiii=f.asm.dynCall_viiiiiiiii).apply(null,arguments)};f.dynCall_viiiiiiii=function(){return(f.dynCall_viiiiiiii=f.asm.dynCall_viiiiiiii).apply(null,arguments)};
f.dynCall_fiiii=function(){return(f.dynCall_fiiii=f.asm.dynCall_fiiii).apply(null,arguments)};f.dynCall_iiiiiiiiiiiiiifii=function(){return(f.dynCall_iiiiiiiiiiiiiifii=f.asm.dynCall_iiiiiiiiiiiiiifii).apply(null,arguments)};f.dynCall_fiifi=function(){return(f.dynCall_fiifi=f.asm.dynCall_fiifi).apply(null,arguments)};f.dynCall_viiiiiii=function(){return(f.dynCall_viiiiiii=f.asm.dynCall_viiiiiii).apply(null,arguments)};f.dynCall_viiiifii=function(){return(f.dynCall_viiiifii=f.asm.dynCall_viiiifii).apply(null,
arguments)};f.dynCall_fii=function(){return(f.dynCall_fii=f.asm.dynCall_fii).apply(null,arguments)};f.dynCall_viiiiiiiiii=function(){return(f.dynCall_viiiiiiiiii=f.asm.dynCall_viiiiiiiiii).apply(null,arguments)};f.dynCall_viiiiiiiiiiii=function(){return(f.dynCall_viiiiiiiiiiii=f.asm.dynCall_viiiiiiiiiiii).apply(null,arguments)};f.dynCall_iiiiiiii=function(){return(f.dynCall_iiiiiiii=f.asm.dynCall_iiiiiiii).apply(null,arguments)};f.dynCall_dd=function(){return(f.dynCall_dd=f.asm.dynCall_dd).apply(null,
arguments)};f.dynCall_viifi=function(){return(f.dynCall_viifi=f.asm.dynCall_viifi).apply(null,arguments)};f.dynCall_fiii=function(){return(f.dynCall_fiii=f.asm.dynCall_fiii).apply(null,arguments)};f.dynCall_viidi=function(){return(f.dynCall_viidi=f.asm.dynCall_viidi).apply(null,arguments)};f.dynCall_did=function(){return(f.dynCall_did=f.asm.dynCall_did).apply(null,arguments)};f.dynCall_fiiiiiiiiffii=function(){return(f.dynCall_fiiiiiiiiffii=f.asm.dynCall_fiiiiiiiiffii).apply(null,arguments)};f.dynCall_viiif=
function(){return(f.dynCall_viiif=f.asm.dynCall_viiif).apply(null,arguments)};f.dynCall_viiiif=function(){return(f.dynCall_viiiif=f.asm.dynCall_viiiif).apply(null,arguments)};f.dynCall_viiiiiiifi=function(){return(f.dynCall_viiiiiiifi=f.asm.dynCall_viiiiiiifi).apply(null,arguments)};f.dynCall_viiijj=function(){return(f.dynCall_viiijj=f.asm.dynCall_viiijj).apply(null,arguments)};f.dynCall_iiiiiiidiiddii=function(){return(f.dynCall_iiiiiiidiiddii=f.asm.dynCall_iiiiiiidiiddii).apply(null,arguments)};
f.dynCall_jij=function(){return(f.dynCall_jij=f.asm.dynCall_jij).apply(null,arguments)};f.dynCall_jii=function(){return(f.dynCall_jii=f.asm.dynCall_jii).apply(null,arguments)};f.dynCall_iiijjji=function(){return(f.dynCall_iiijjji=f.asm.dynCall_iiijjji).apply(null,arguments)};f.dynCall_iiiji=function(){return(f.dynCall_iiiji=f.asm.dynCall_iiiji).apply(null,arguments)};f.dynCall_jiiij=function(){return(f.dynCall_jiiij=f.asm.dynCall_jiiij).apply(null,arguments)};f.dynCall_v=function(){return(f.dynCall_v=
f.asm.dynCall_v).apply(null,arguments)};f.dynCall_iiifii=function(){return(f.dynCall_iiifii=f.asm.dynCall_iiifii).apply(null,arguments)};f.dynCall_iidiiii=function(){return(f.dynCall_iidiiii=f.asm.dynCall_iidiiii).apply(null,arguments)};f.dynCall_iij=function(){return(f.dynCall_iij=f.asm.dynCall_iij).apply(null,arguments)};f.dynCall_iiiiiiiiii=function(){return(f.dynCall_iiiiiiiiii=f.asm.dynCall_iiiiiiiiii).apply(null,arguments)};f.dynCall_viiiiiiiiiii=function(){return(f.dynCall_viiiiiiiiiii=f.asm.dynCall_viiiiiiiiiii).apply(null,
arguments)};f.asm=wb;var Ea;ka=function b(){Ea||Qa();Ea||(ka=b)};f.run=Qa;if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var mb=!0;f.noInitialRun&&(mb=!1);Qa();return qb};
